eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# the key we are passing to the microservice instead of direct url is from microservice till uri below, so we get value using value annotation.

microservice:
  paymentservice:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  orderservice:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
